# STOMP Auto-Scaling Service Configuration Template
# Copy this file to config.yaml and update with your settings

# Service metadata
service:
  name: "stomp-service"
  version: "1.0.0"
  description: "Production STOMP messaging service"

# Broker configuration (supports both ActiveMQ and Artemis)
broker:
  type: "activemq"                    # Broker type: "activemq" or "artemis"
  host: "localhost"                   # Broker server hostname or IP
  username: "admin"                   # STOMP authentication username
  password: "admin"                   # STOMP authentication password
  stomp_port: 61613                  # STOMP messaging port (default: 61613)
  web_port: 8161                     # Broker web console port (default: 8161)
  heartbeat_secs: 30                 # Connection heartbeat interval in seconds
  broker_name: "localhost"           # Broker name (ActiveMQ: "localhost", Artemis: "broker")

# Message destinations
destinations:
  # Queue configurations - competing consumers (load balancing)
  queues:
    default: "/queue/demo"             # Default queue for general messages
    api_requests: "/queue/api.requests" # API request handling queue
    errorsx: "/queue/errorsx"            # Error handling queue
  
  # Topic configurations - broadcast to all subscribers
  topics:
    notifications: "/topic/notifications"            # System notifications topic

# Auto-scaling configuration
scaling:
  enabled: true                       # Enable/disable auto-scaling
  interval_secs: 5                    # Monitor queue metrics every N seconds
  
  # Worker scaling rules per queue
  # Format: "min-max" for auto-scaling or "count" for fixed workers
  workers:
    # Auto-scaling examples (format: "min-max")
    default: "1-4"                    # Scale between 1-4 workers based on queue depth
    api_requests: "3-10"              # High-priority queue with 3-10 workers
    
    # Fixed worker count examples (format: "count")  
    errorsx: "2"                       # Always maintain exactly 2 error handlers

# Consumer configuration  
consumers:
  ack_mode: "auto"                    # Message acknowledgment mode: "auto", "client", "client-individual"

# Logging configuration
logging:
  level: "info"                       # Log level: "trace", "debug", "info", "warn", "error"
  output: "stdout"                    # Output: "stdout", "stderr", or file path

# Service shutdown configuration
shutdown:
  timeout_secs: 30                   # Maximum time to wait for graceful shutdown
  grace_period_secs: 5               # Grace period before forcing shutdown

# Retry configuration for connections and operations
retry:
  max_attempts: -1                     # Maximum retry attempts (-1 for infinite)
  initial_delay_ms: 1000             # Initial delay between retries (1 second)
  max_delay_ms: 30000                # Maximum delay cap (30 seconds)
  backoff_multiplier: 2.0            # Exponential backoff multiplier